### ISSUE TITLE
Text alignment issue when left menu text spans two lines

### ISSUE THREAD

**Issue by sebemra** [sebgroup/ng-wizard#89]
The alignment of the text is off when the text in the left menu spans over two lines, see image:

![left-menu](https://user-images.githubusercontent.com/92314929/136800490-79d5cc13-9452-4a74-baa1-e22b6d14d94a.jpg)

**Comment by sebemra** [comment]
Hi, just tested the fix. It is working much better but it needs some more space between the text and icon:
![image](https://user-images.githubusercontent.com/92314929/146162981-50636a90-ae36-401a-9df6-a9e4f02df385.png)

**Comment by hjalmers** [comment]
@sebemra thanks for noticing and reporting, should be fixed now with 3.2.0:)
